server:
  port: 8082

logging:
  level:
    root: ${LOGGING_LEVEL:info}
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: INFO
            repository:
                query: INFO
    "[com.totem.food]": ${APP_LOGGING_LEVEL:debug}
    "[org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping]": ${SHOW_ENDPOINTS_LOGGING_LEVEL:info}
  pattern:
    level: "%clr(${LOG_LEVEL_PATTERN: [%X{x-request-id}] [%X{x-environment-id}] [%X{x-customer-id}] -%5p})"

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: ${HIBERNATE_SHOW_QUERY:false}
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_QUERY:false}
        dialect: org.hibernate.dialect.MySQL8Dialect
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: ${PAYMENT_DB_URL:jdbc:mysql://localhost:3306/db_payment?createDatabaseIfNotExist=true}
    username: ${PAYMENT_DB_USERNAME:root}
    password: ${PAYMENT_DB_PASSWORD:qwe123}
  liquibase:
    change-log: classpath:/db/master.xml


payment:
  url: ${PAYMENT_GATEWAY_URL:https://api.mercadopago.com}
  callback: ${PAYMENT_CALLBACK_URL:https://composed-firefly-willingly.ngrok-free.app/v1/totem/payment/callback}
  store_id: ${STORE_ID:}
  store_user_id: ${STORE_USER_ID:}
  store_token_id: ${STORE_TOKEN:}

app:
  version: ^project.version^
  name: ^project.name^
  description: ^project.description^
  inspect_beans: ${INSPECT_BEANS:false}

ms:
  internal:
    order:
      url: ${MS_INTERNAL_ORDER:http://localhost:8080}
    customer:
      url: ${MS_INTERNAL_CUSTOMER:http://localhost:8081}

liquibase:
  change-log: classpath:liquibase-changeLog.xml